#  this is the example of case_file
#  .toml format
[main]
in = """
Comet can fly 14 km/s for 10 seconds, but then must rest for 127 seconds.
Dancer can fly 16 km/s for 11 seconds, but then must rest for 162 seconds.
"""
out = "1120"  # output may not be specified - "?"

