#  this is the example of case file
#  .toml format
[main]
in = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."""
out = "41"  # ? - output is not specified
time = 5   # TLE timeout. Optional (1 is default)
