#  this is the example of case file
#  .toml format
[main]
in = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
out = "14"  # ? - output is not specified
time = 1   # TLE timeout. Optional (1 is default)
