#  this is the example of case file
#  .toml format
[main]
in = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""
out = "9"  # ? - output is not specified
time = 1   # TLE timeout. Optional (1 is default)
